# config.yaml - beets configuration

directory: ~/music

# load some useful plug-ins
plugins: fetchart lastgenre lyrics mbsync

# get rid of localized characters
asciify_paths: yes

# art cover compatible with Windows
art_filename: Folder

paths:
  default: "$albumartist/[$original_year] $album/$track $title"
  singleton: "$artist/[$original_year] $title"
  comp: "!Compilations/[$original_year] $album/$track $title"
  albumtype:soundtrack: "!Soundtracks/[$original_year] $album/$track $title"

fetchart:
  cautious: true
  enforce_ratio: yes
  maxwidth: 600

lastgenre:
  canonical: ""
